import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { SidebarProvider } from "@/context/SidebarContext";
import QueryClientContext from "@/context/QueryClientContext";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import 'antd/dist/reset.css';
import Notification from "./notification";
import NotificationProvider from "@/context/NotificationContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} dark:bg-gray-900`}>
        <NotificationProvider>
          <AntdRegistry>
            <QueryClientContext>
              <ThemeProvider>
                <SidebarProvider>
                  {children}
                </SidebarProvider>
              </ThemeProvider>
            </QueryClientContext>
          </AntdRegistry>
        </NotificationProvider>
      </body>
    </html>
  );
}
